trigger:
- none

resources:
- repo: self

variables:
  ACR_NAME: 'crsanyi'
  IMAGE_NAME: 'sanyiapp:$(Build.BuildId)'
  IMAGE_REPOSITORY: 'crsanyi.azurecr.io/sanyiapp'
  TAG: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Build an image
      inputs:
        azureSubscription: 'ZEISSgroup-DI05-ASM-Learning'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME -f $(Build.SourcesDirectory)/app/Dockerfile
          az acr login --name $ACR_NAME
          docker tag $IMAGE_NAME $ACR_NAME.azurecr.io/$IMAGE_NAME
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    dockerhubsecret: dhauth
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool: 
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)/manifests'

    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'aks-sanyi-default'
        namespace: 'defualt'
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yml
          $(Pipeline.Workspace)/manifests/service.yml
