apiVersion : apps/v1
kind: Deployment
metadata:
  name: sanyi-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sanyi-app
  template:
    metadata:
      labels:
        app: sanyi-app 
    spec:
      containers:
        - name: sanyi-app 
          image: interiordesign/demo/sanyi-app
          ports:
          - containerPort: 80